server:
  port: 8081
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/miooyuki_docsys?serverTimezone=Asia/Shanghai"
    username: "root"
    password: "123456"